### ISSUE TITLE
base modification information basecalling through sim_read_until

### ISSUE THREAD

**Issue by shuyi122425** [ratschlab/sim_read_until#1]
Hi, I have a question about sim_read_until. It has been mentioned that the modified ReadUntil API provides basecalled reads instead of raw signal in the preprint version. Therefore, I am unable to obtain the raw signal file using this API if I intend to extract some base modification information from the fast5 files. Is that right?

**Comment by maximilianmordig** [comment]
Yes, that's right, the main focus is on basecalled data right now. I have implemented a basic version using a pore model that repeats the k-mer mean 10 times in the ReadUntil API. I didn't test it yet and it is not available via gRPC, you can access it by instantiating the simulator directly and call `get_raw_chunks`:
https://github.com/ratschlab/sim_read_until/blob/f71e34df7f92ee26648e7d59758d6a5e9ef4fe91/src/simreaduntil/simulator/simulator.py#L586C14-L586C14

The simulator persists fasta files instead of fast5 files. If enough people are interested, I can combine it with a tool like Squigulator (pore model + noise essentially) to create blow5 files (or pod5). Outputting fast5 files is probably too slow and blow5 is an excellent well-supported alternative.
